import { webcrypto } from 'node:crypto';
// Parche para Node 18 (Crypto global)
if (!globalThis.crypto) {
  Object.defineProperty(globalThis, 'crypto', {
    value: webcrypto,
    writable: false,
    configurable: true
  });
}

import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { ConfigService } from '@nestjs/config';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  
  // 1. Prefijo Global (Vital para que coincida con Apache)
  //app.setGlobalPrefix('api-mylexicon');

  const configService = app.get(ConfigService);
  const isDeploy = configService.get<string>('DEPLOY') === 'true';

  const frontendUrl = isDeploy
    ? configService.get<string>('FRONTEND_URL_DEPLOY')
    : configService.get<string>('FRONTEND_URL_LOCAL');

  const backendUrl = isDeploy
    ? configService.get<string>('BACKEND_URL_DEPLOY')
    : configService.get<string>('BACKEND_URL_LOCAL');

  // --- HABILITAR CORS ---
  app.enableCors({
    origin: frontendUrl,
    methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
    credentials: true,
  });

  // --- Swagger Api Docs ---
  const config = new DocumentBuilder()
    .setTitle('MyLexicon API Documentation')
    .addBearerAuth()
    .setDescription('Autogenerated by swagger.')
    .setVersion('1.0.0')
    .build();

  const document = SwaggerModule.createDocument(app, config);
  
  // 3. Setup de Swagger: Debe apuntar a 'api' dentro del contexto del prefijo
  // La URL real será: jescarcon.ddns.net/api-mylexicon/api
  SwaggerModule.setup('api-mylexicon/api', app, document);

  // Iniciar servidor
  await app.listen(process.env.PORT ?? 3000,'0.0.0.0');

  console.log(`\n🚀 MyLexicon API is running!`);
  console.log(`📡 Backend URL: ${backendUrl}`);
  console.log(`🔗 Swagger UI:  ${backendUrl}/api`);
  console.log(`🔐 Frontend CORS: ${frontendUrl}\n`);
}
bootstrap();
