import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { ValidationPipe } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

async function bootstrap() {

  const app = await NestFactory.create(AppModule);
 
  //Swagger Api Docs
  const config = new DocumentBuilder()
    .setTitle('MyLexicon API Documentation')
    .addBearerAuth()
    .setDescription('Autogenerated by swagger.')
    .setVersion('1.0.0')
    .build();

  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('api', app, document);
  //Swagger Api Docs

  await app.listen(process.env.PORT ?? 3000);

  console.log(`Server running on http://localhost:${process.env.PORT ?? 3000}`);
}
bootstrap();
